=== Irene-Frias/1DAM-Cross-Platform-Application-Development/Markup-Language/UNIT 4 - Validation DTD - XML Schema and XML - XML/XML Schema - XML/A404/ejercicio1/Vehiculos.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="vehiculos">
        <xs:complexType>
          <xs:sequence>

            <xs:element name="vehiculo" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="nombre" type="xs:string"/>
                  <xs:element name="modelo" type="xs:string"/>

                  <xs:element name="fabricacion">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="inicio">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="dia" type="xs:int"/>
                              <xs:element name="mes" type="xs:string"/>
                              <xs:element name="anyo" type="xs:int"/>
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                        <xs:element name="fin">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="dia" type="xs:int"/>
                              <xs:element name="mes" type="xs:string"/>
                              <xs:element name="anyo" type="xs:int"/>
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="modificaciones" minOccurs="0">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="modificacion" maxOccurs="unbounded">
                          <xs:complexType>
                            <xs:simpleContent>
                              <xs:extension base="xs:string">
                                <xs:attribute name="pagada" type="xs:boolean" default="false"/>
                              </xs:extension>
                            </xs:simpleContent>
                          </xs:complexType>
                        </xs:element>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
                <xs:attribute name="num-serie" type="xs:string"></xs:attribute>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Irene-Frias/1DAM-Cross-Platform-Application-Development/Markup-Language/UNIT 4 - Validation DTD - XML Schema and XML - XML/XML Schema - XML/A404/ejercicio1/vehiculos.xml
<?xml version="1.0" encoding="utf-8"?>
<vehiculos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Vehiculos.xsd">
  <vehiculo num-serie="12345678">
    <nombre>Seat Ibiza</nombre>
    <modelo>GTI+</modelo>
    <fabricacion>
      <inicio>
        <dia>21</dia>
        <mes>Julio</mes>
        <anyo>1992</anyo>
      </inicio>
      <fin>
        <dia>9</dia>
        <mes>Agosto</mes>
        <anyo>1992</anyo>
      </fin>
    </fabricacion>
    <modificaciones>
      <modificacion pagada="true">Aumento cilindrada 2000cc</modificacion>
      <modificacion>Pedales deportivos</modificacion>
      <modificacion pagada="false">Caja de cambios 6 velocidades</modificacion>
      <modificacion>Diferencial autoblocante</modificacion>
    </modificaciones>
  </vehiculo>
  <vehiculo num-serie="87654321">
    <nombre>Hyundai Coup√©</nombre>
    <modelo>Turbo</modelo>
    <fabricacion>
      <inicio>
        <dia>21</dia>
        <mes>Septiembre</mes>
        <anyo>2004</anyo>
      </inicio>
      <fin>
        <dia>24</dia>
        <mes>Septiembre</mes>
        <anyo>2004</anyo>
      </fin>
    </fabricacion>
  </vehiculo>
</vehiculos>
