=== Irene-Frias/1DAM-Cross-Platform-Application-Development/UNIT 4 - Validation DTD - XML Schema and XML - XML/XML Schema - XML/A408/Receta de cocina/recetas.xsd
<?xml version="1.0"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:simpleType name="tTiempo">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="5"/>
            <xs:maxInclusive value="300"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="tDificultad">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Facil"/>
            <xs:enumeration value="Media"/>
            <xs:enumeration value="Dificil"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="tUnidad">
        <xs:restriction base="xs:string">
            <xs:enumeration value="gr"/>
            <xs:enumeration value="l"/>
            <xs:enumeration value="ml"/>
            <xs:enumeration value="cucharadas"/>
            <xs:enumeration value="pieza"/>
             <xs:enumeration value="piezas"/>
            <xs:enumeration value="dientes"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="tCalorias">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="50"/>
            <xs:maxInclusive value="200"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="tGrasa">
        <xs:restriction base="xs:decimal">
            <xs:totalDigits value="5"/> 
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="tProteina">
        <xs:restriction base="xs:decimal">
            <xs:totalDigits value="5"/> 
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    
    <xs:element name="recetas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="receta" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="tiempo" type="tTiempo"/>
                            <xs:element name="dificultad" type="tDificultad"/>
                            
                            <xs:element name="ingredientes" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ingrediente" minOccurs="1"
                                            maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string"/>
                                                    <xs:element name="cantidad" type="xs:decimal"/>
                                                    <xs:element name="unidad" type="tUnidad"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            
                            <xs:element name="pasos" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="paso" minOccurs="1"
                                            maxOccurs="unbounded">
                                        
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            
                            <xs:element name="descripcion" minOccurs="0" maxOccurs="1">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="tiempo" type="xs:string"/>
                                        <xs:element name="temperatura" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            
                            <xs:element name="nutricion" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="calorias" type="tCalorias"/>
                                        <xs:element name="grasa" type="tGrasa"/>
                                        <xs:element name="proteina" type="tProteina"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>    
    </xs:element>
</xs:schema>

=== Irene-Frias/1DAM-Cross-Platform-Application-Development/UNIT 4 - Validation DTD - XML Schema and XML - XML/XML Schema - XML/A408/Recetas/recetas.xml
<?xml version="1.0" encoding="UTF-8"?>
<recetas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="recetas.xsd">
    <receta>
        <nombre>Spaghetti Aglio e Olio</nombre>
        <tiempo>20</tiempo>
        <dificultad>Facil</dificultad>
        <ingredientes>
            <ingrediente>
                <nombre>Spaghetti</nombre>
                <cantidad>200</cantidad>
                <unidad>gr</unidad>
            </ingrediente>
            <ingrediente>
                <nombre>Ajo</nombre>
                <cantidad>4</cantidad>
                <unidad>dientes</unidad>
            </ingrediente>
            <ingrediente>
                <nombre>Aceite de oliva</nombre>
                <cantidad>50</cantidad>
                <unidad>ml</unidad>
            </ingrediente>
            <ingrediente>
                <nombre>Guindilla</nombre>
                <cantidad>1</cantidad>
                <unidad>pieza</unidad>
            </ingrediente>
        </ingredientes>


        <pasos>
            <paso>Poner agua con sal a hervir y cocinar los spaghetti 
                según las indicaciones del paquete.</paso>
            <paso>En una sartén grande, calentar el aceite de oliva y 
                dorar los ajos picados y la guindilla.</paso>
            <paso>Escurrir la pasta y mezclarla con el aceite 
                aromatizado.</paso>
        </pasos>
        <descripcion>
            Este plato italiano es perfecto para una comida rápida y sabrosa.
            <tiempo>15 minutos</tiempo>
            <temperatura>Media</temperatura>
        </descripcion>
        <nutricion>
            <calorias>400</calorias>
            <grasa>20</grasa>
            <proteina>10</proteina>                            
        </nutricion>
    </receta>

    <receta>
        <nombre>Ensalada César</nombre>
        <tiempo>15</tiempo>
        <dificultad>Facil</dificultad>
        <ingredientes>
            <ingrediente>
                <nombre>Lechuga romana</nombre>
                <cantidad>200</cantidad>
                <unidad>gr</unidad>
            </ingrediente>
            <ingrediente>
                <nombre>Pechuga de pollo</nombre>
                <cantidad>150</cantidad>
                <unidad>gr</unidad>
            </ingrediente>
            <ingrediente>
                <nombre>Pan tostado</nombre>
                <cantidad>50</cantidad>
                <unidad>gr</unidad>
            </ingrediente>
            <ingrediente>
                <nombre>Queso parmesano</nombre>
                <cantidad>30</cantidad>
                <unidad>gr</unidad>
            </ingrediente>
            <ingrediente>
                <nombre>Salsa César</nombre>
                <cantidad>2</cantidad>
                <unidad>cucharadas</unidad>
            </ingrediente>
        </ingredientes>

        <pasos>
            <paso>Lavar y cortar la lechuga en trozos medianos.</paso>
            <paso>Freír la pechuga de pollo y cortarla en tiras.</paso>
            <paso>Mezclar la lechuga, pollo, pan tostado y queso en 
                un bol grande.</paso>
            <paso>Agregar la salsa César y mezclar bien.</paso>
        </pasos>
    </receta>        
</recetas>
