=== Irene-Frias/1DAM-Cross-Platform-Application-Development/Markup-Language/UNIT 4 - Validation DTD - XML Schema and XML - XML/DTD - XML/A404/Peliculas/peliculas.dtd
<!ELEMENT peliculas (pelicula+)>
<!ELEMENT pelicula (titulo, director, anyoestreno, genero, duracion, actores+, 
                    sinopsis?)>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT anyoestreno (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT actores (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>
<!ATTLIST pelicula id ID #REQUIRED>

=== Irene-Frias/1DAM-Cross-Platform-Application-Development/Basic XML y DTD/A404/Peliculas/peliculas.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE peliculas SYSTEM "peliculas.dtd">

<peliculas>
    <pelicula id="C-10">
        <titulo>Pulp Fiction</titulo>
        <director>Quentin Tarantino</director>
        <anyoestreno>1994</anyoestreno>
        <genero>Acción</genero>
        <duracion>1 hora y 30 min</duracion>
        <actores>John Travolta</actores>
        <sinopsis>Jules y Vincent, dos asesinos a sueldo con 
            no demasiadas luces, trabajan para el gángster Marsellus 
            Wallace. Vincent le confiesa a Jules que Marsellus le ha
            pedido que cuide de Mia, su atractiva mujer. Jules le 
            recomienda prudencia porque es muy peligroso sobrepasarse 
            con la novia del jefe. Cuando llega la hora de trabajar, 
            ambos deben ponerse "manos a la obra". Su misión: recuperar
            un misterioso maletín.</sinopsis>
    </pelicula>
    <pelicula id="C-11">
        <titulo>El padrino</titulo>
        <director>Francis Ford Coppola</director>
        <anyoestreno>1972</anyoestreno>
        <genero>Acción</genero>
        <duracion>1 hora y 45 min</duracion>
        <actores>Marlon Brando</actores>
        <actores>Al Pacino</actores>
        <actores>James Caan</actores>
    </pelicula>
</peliculas>
