=== Irene-Frias/1DAM-Cross-Platform-Application-Development/UNIT 4 - Validation DTD - XML Schema and XML - XML/XML Schema - XML/A407/Libro/libro.xsd
<?xml version="1.0"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="libro">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo" type="xs:string"/>
                <xs:element name="autor" type="xs:string"/>            
                <xs:element name="capitulo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="p" maxOccurs="unbounded">
                                <xs:complexType mixed="true">
                                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                                        <xs:element name="mi" type="xs:string"/>
                                        <xs:element name="i" type="xs:string"/>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element> 
                        </xs:sequence>            
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Irene-Frias/1DAM-Cross-Platform-Application-Development/Markup-Language/UNIT 4 - Validation DTD - XML Schema and XML - XML/XML Schema - XML/A407/Libro/libro.xml
<?xml version="1.0" encoding="UTF-8"?>
<libro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="libro.xsd">
    <titulo>XML F치cil</titulo>
    <autor>Laura</autor>
    <capitulo>
        <titulo>Introducci칩n</titulo>
        <p>Primeros pasos en <mi>XML</mi>.</p>
        <p>C칩mo usar <i>estructuras b치sicas</i>.</p>
    </capitulo>
</libro>
