=== Irene-Frias/1DAM-Cross-Platform-Application-Development/Markup-Language/UNIT 4 - Validation DTD - XML Schema and XML - XML/XML Schema - XML/A403/Cancion.xsd
<?xml version="1.0"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="cancion">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="tipo" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="anyo" type="xs:gYear"/>
                <xs:element name="duracion" type="xs:string"/>
                <xs:element name="artistas">
                    <xs:complexType>
                            <xs:sequence>
                                <xs:element name="artista" type="xs:string" 
                                            maxOccurs="unbounded"/>
                            </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="letra">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="estrofa" maxOccurs="unbounded">
                                <xs:complexType>
                                  <xs:sequence>
                                    <xs:element name="linea" type="xs:string" 
                                                maxOccurs="unbounded"/>
                                  </xs:sequence>
                                  <xs:attribute name="artista" type="xs:string" 
                                                use="required"/>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Irene-Frias/1DAM-Cross-Platform-Application-Development/Markup-Language/UNIT 4 - Validation DTD - XML Schema and XML - XML/XML Schema - XML/A402 - XML Schema No Válidos/WeAreTheWorld.xml
<?xml version="1.0"?>
<cancion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Cancion.xsd">
	<titulo>We Are The World</titulo>
	<artistas>
		<artista>Willie Nelson</artista>
		<artista>Cyndi Lauper</artista>
		<artista>Billy Joel</artista>
		<artista>Paul Simon</artista>
		<artista>Stevie Wonder</artista>
	</artistas>
	<año>1985</año>
</cancion>
