=== Irene-Frias/1DAM-Cross-Platform-Application-Development/Basic XML y DTD/A404/EventosCulturales/eventos.dtd
<!ELEMENT eventos (evento+)>

<!ELEMENT evento (nombre, fecha, hora, lugar, informacion?, (gratuito | pago)?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT lugar (#PCDATA)>
<!ATTLIST evento codigo ID #REQUIRED>
<!ELEMENT informacion (#PCDATA)>
<!ELEMENT gratuito (#PCDATA)>
<!ELEMENT pago (#PCDATA)>

=== Irene-Frias/1DAM-Cross-Platform-Application-Development/Basic XML y DTD/A404/EventosCulturales/eventos .xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE eventos SYSTEM "eventos.dtd">

<eventos>
    <evento codigo="C-202">
        <nombre>Fiesta</nombre>
        <fecha>06-03-2025</fecha>
        <hora>23:00</hora>
        <lugar>La Curiosa</lugar>
        <informacion>dfsd</informacion>
        <gratuito>Gratis</gratuito>
    </evento>
    <evento codigo="C-303">
        <nombre>Boda</nombre>
        <fecha>18-03-2025</fecha>
        <hora>10:00</hora>
        <lugar>Valtari</lugar>
        <pago>20000</pago>
    </evento>
</eventos>
