=== Irene-Frias/1DAM-Cross-Platform-Application-Development/UNIT 4 - Validation DTD - XML Schema and XML - XML/XML Schema - XML/A404/ejercicio4/Vivienda.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:simpleType name="tipoHabitacion">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Sala de estar"/>
            <xs:enumeration value="Dormitorio"/>
            <xs:enumeration value="Cocina"/>
            <xs:enumeration value="Salón"/>
            <xs:enumeration value="Cuarto de baño"/>
            <xs:enumeration value="Terraza"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="enteroMayorQueCero">
        <xs:restriction base="xs:integer">
            <xs:minExclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="enteroMayorIgualCero">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="decimalMayorQueCero">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="vivienda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="habitacion" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="puertas" type="enteroMayorQueCero"/>
                            <xs:element name="ventanas" type="enteroMayorIgualCero"/>
                            <xs:element name="suelo">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="decimalMayorQueCero">
                                            <xs:attribute name="parquet" type="xs:boolean" use="optional"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="electricidad">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="luces" type="enteroMayorIgualCero"/>
                                        <xs:element name="interruptores" type="enteroMayorIgualCero"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="tipo" type="tipoHabitacion" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Irene-Frias/1DAM-Cross-Platform-Application-Development/Markup-Language/UNIT 4 - Validation DTD - XML Schema and XML - XML/XML Schema - XML/A404/ejercicio4/vivienda.xml
<?xml version="1.0" encoding="UTF-8"?>
<vivienda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Vivienda.xsd">
  <habitacion tipo="Sala de estar">
    <puertas>2</puertas>
    <ventanas>3</ventanas>
    <suelo parquet="true">40</suelo>
    <electricidad>
      <luces>5</luces>
      <interruptores>3</interruptores>
    </electricidad>
  </habitacion>

  <habitacion tipo="Dormitorio">
    <puertas>1</puertas>
    <ventanas>1</ventanas>
    <suelo>10</suelo>
    <electricidad>
      <luces>3</luces>
      <interruptores>5</interruptores>
    </electricidad>
  </habitacion>
</vivienda>
