=== Irene-Frias/1DAM-Cross-Platform-Application-Development/Basic XML y DTD/A404/CursosFormacion/cursosformacion.dtd
<!ELEMENT cursos (curso+)>
<!ELEMENT curso (nombre, duracion, profesor, horario, alumno+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT profesor (#PCDATA)>
<!ELEMENT horario (#PCDATA)>
<!ATTLIST curso codigo ID #REQUIRED>
<!ELEMENT alumno (nombre, matricula, comentario?)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT comentario (#PCDATA)>

=== Irene-Frias/1DAM-Cross-Platform-Application-Development/Markup-Language/UNIT 4 - Validation DTD - XML Schema and XML - XML/DTD - XML/A404/CursosFormacion/cursosformacion.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cursos SYSTEM "cursosformacion.dtd">

<cursos>
    <curso codigo="C-100">
        <nombre>Introducción a bases de datos</nombre>
        <duracion>3 horas</duracion>
        <profesor>María</profesor>
        <horario>Mañana</horario>
        <alumno>
            <nombre>Rafael</nombre>
            <matricula>1245785891</matricula>
        </alumno>
        <alumno>
            <nombre>Sergio</nombre>
            <matricula>2345678924</matricula>
            <comentario>Tiene que esforzarse más</comentario>
        </alumno>        
    </curso>
    <curso codigo="C-101">
        <nombre>Introducción a Lenguajes de Marcas</nombre>
        <duracion>2 horas</duracion>
        <profesor>Manolo</profesor>
        <horario>Mañana</horario>
        <alumno>
            <nombre>Francisco</nombre>
            <matricula>02456851565</matricula>
            <comentario>Trabajador</comentario>
        </alumno>
        <alumno>
            <nombre>Pedro</nombre>
            <matricula>12456789524</matricula>
        </alumno>
    </curso>    
</cursos>
