=== Irene-Frias/1DAM-Cross-Platform-Application-Development/UNIT 4 - Validation DTD - XML Schema and XML - XML/XML Schema - XML/A404/ejercicio3/Cadenas.xsd
<?xml version="1.0"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="tipoAltura">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
   
    <xs:simpleType name="unidadMedidaTipo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="m"/>
            <xs:enumeration value="f"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nombreMayuscula">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z].*"/>
        </xs:restriction>
    </xs:simpleType>
        
    <xs:element name="cadenas-montanyosas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cadena-montanyosa" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>                                                        
                            <xs:element name="montanya" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="region" type="xs:string"/>
                                        <xs:element name="altura">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="tipoAltura">
                                                        <xs:attribute name="unidad-medida" type="unidadMedidaTipo" use="optional"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>    
                        </xs:sequence>
                        <xs:attribute name="nombre" type="nombreMayuscula" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Irene-Frias/1DAM-Cross-Platform-Application-Development/UNIT 4 - Validation DTD - XML Schema and XML - XML/XML Schema - XML/A404/ejercicio3/cadenas.xml
<?xml version="1.0" encoding="UTF-8"?>
<cadenas-montanyosas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Cadenas.xsd">
  <cadena-montanyosa nombre="Pirineos">
    <montanya>
      <nombre>Pico Aneto</nombre>
      <region>Maladeta-Aneto</region>
      <altura unidad-medida="m">3404</altura>
    </montanya>
    <montanya>
      <nombre>Sierra Morena</nombre>
      <region>La Múnia</region>
      <altura unidad-medida="m">3090</altura>
    </montanya>
  </cadena-montanyosa>
  <cadena-montanyosa nombre="Sierra Nevada">
    <montanya>
      <nombre>Mulhacén</nombre>
      <region>Sierra norte</region>
      <altura unidad-medida="m">3480</altura>
    </montanya>
    <montanya>
      <nombre>Cartujo</nombre>
      <region>Sierra sur</region>
      <altura unidad-medida="m">3152</altura>
    </montanya>
  </cadena-montanyosa>
</cadenas-montanyosas>
