=== Irene-Frias/1DAM-Cross-Platform-Application-Development/Markup-Language/UNIT 4 - Validation DTD - XML Schema and XML - XML/DTD - XML/A403/ejercicio1/alumnos.dtd
<!ELEMENT alumnos (alumno*)>
<!ELEMENT alumno (nombre, apellidos, domicilio, telefono*, centroDeportivo?, aficion*,
                  (provincia | pais), comentarios, (evaluacion, calificacion)*)>
<!ATTLIST alumno numAlumno ID #REQUIRED
                 altura CDATA #IMPLIED
                 sexo (hombre | mujer) #IMPLIED
                 ayudadoPor IDREF #IMPLIED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT domicilio (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>

<!ATTLIST telefono pertenece (propio | madre | padre | tutor) #REQUIRED>

<!ELEMENT centroDeportivo (#PCDATA)>
<!ELEMENT aficion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT comentarios (#PCDATA)>
<!ELEMENT evaluacion (#PCDATA)>
<!ELEMENT calificacion (#PCDATA)>

=== Irene-Frias/1DAM-Cross-Platform-Application-Development/Basic XML y DTD/A403/ejercicio1/alumnos.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE alumnos SYSTEM "alumnos.dtd">

<alumnos>
    <alumno numAlumno="A-01" altura="1,60" sexo="mujer" ayudadoPor="A-02">
        <nombre>María</nombre>
        <apellidos>Jiménez</apellidos>
        <domicilio>Calle Carlton</domicilio>
        <telefono pertenece="padre">+34 678 458 219</telefono>
        <centroDeportivo>Puerta Oscura</centroDeportivo>
        <aficion>Baloncesto</aficion>
        <aficion>Leer</aficion>
        <provincia>Málaga</provincia>
        <comentarios>Muy trabajadora</comentarios>
        <evaluacion>Primera</evaluacion>
        <calificacion>8,23</calificacion>
    </alumno>
    <alumno numAlumno="A-02" altura="1,68" sexo="hombre">
        <nombre>Paco</nombre>
        <apellidos>Martínez</apellidos>
        <domicilio>Pasaje Aurora</domicilio>
        <telefono pertenece="madre">+34 656 558 913</telefono>
        <telefono pertenece="tutor">+34 758 425 785</telefono>
        <aficion>Videojuegos</aficion>
        <pais>Italia</pais>
        <comentarios>Debe trabajar más</comentarios>
        <evaluacion>Primera</evaluacion>
        <calificacion>6,12</calificacion>
    </alumno>
</alumnos>
