=== Irene-Frias/1DAM-Cross-Platform-Application-Development/Basic XML y DTD/A404/GestionEmpleados/gestionempleados.dtd
<!ELEMENT empleados (empleado+)>
<!ELEMENT empleado (nombre, apellidos, cargo, departamento, salario, telefono,
                    proyecto?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT cargo (#PCDATA)>
<!ELEMENT departamento (#PCDATA)>            
<!ELEMENT salario (#PCDATA)>
<!ELEMENT proyecto (nombre, fecha)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>

<!ATTLIST telefono dispositivo (movil | fijo) #REQUIRED>
<!ATTLIST empleado id_empleado ID #REQUIRED>

=== Irene-Frias/1DAM-Cross-Platform-Application-Development/Basic XML y DTD/A404/GestionEmpleados/gestionempleados.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE empleados SYSTEM "gestionempleados.dtd">

<empleados>
    <empleado id_empleado="E-020">
        <nombre>Eustaquio</nombre>
        <apellidos>Jiménez</apellidos>
        <cargo>administrativo</cargo>
        <departamento>Recursos Humanos</departamento>
        <salario>1500</salario>
        <telefono dispositivo="movil">+34 651 254 581</telefono>
    </empleado>
    <empleado id_empleado="E-021">
        <nombre>Lucía</nombre>
        <apellidos>Martínez</apellidos>
        <cargo>administrativo</cargo>
        <departamento>Marketing</departamento>
        <salario>1600</salario>
        <telefono dispositivo="fijo">+34 651 254 581</telefono>
        <proyecto>
            <nombre>Misterio</nombre>
            <fecha>04-02-2025</fecha>
        </proyecto>
    </empleado>
</empleados>
